name: Build ChatBrowser Win

on:
  workflow_dispatch:  # This enables the manual trigger

jobs:
  run-manually:
    runs-on: windows-2019
    permissions:
      contents: read
      deployments: write
    name: Deploy Amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: auto
        run: |
          call C:\Miniconda\Scripts\activate.bat
        shell: cmd



