on: [ push ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Choose the Python version you need
      - name: Install MkDocs and Dependencies
        run: |
          pip install mkdocs
      - name: Build MkDocs Documentation
        run: |
          mkdocs build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.ACCOUNTID }}
          projectName: "chat-manual"
          directory: "site"
          branch: main
          wranglerVersion: '3'